services:
  lumina-app:
    build: .
    container_name: lumina_engine
    ports:
      - "8000:8000"
    environment:
      - LOG_LEVEL=INFO
      - GROQ_API_KEY=${GROQ_API_KEY}
    volumes:
      - ./lumina_sessions.db:/app/lumina_sessions.db
    restart: unless-stopped